version: "2.12"

services:

  mongo1:
    container_name: mongo1
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27017:27017
    networks:
      mongo-cluster:
        ipv4_address: 172.20.0.2
    volumes:
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js
      - ./mongo-rs/rs_keyfile:/etc/mongodb/pki/keyfile
      - "mongo1_data:/data/db"
      - "mongo_config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: SeedAdmin
      MONGO_INITDB_ROOT_PASSWORD: SeedTest
      MONGO_INITDB_DATABASE: Seed

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    command: ["--replSet", "rs0" ,"--bind_ip_all", "--port", "27018","--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27018:27018
    networks:
      mongo-cluster:
        ipv4_address: 172.20.0.3
    volumes:
      - ./mongo-rs/rs_keyfile:/etc/mongodb/pki/keyfile
      - "mongo2_data:/data/db"
      - "mongo_config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: SeedAdmin
      MONGO_INITDB_ROOT_PASSWORD: SeedTest

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    command: ["--replSet", "rs0" ,"--bind_ip_all", "--port", "27019","--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27019:27019
    networks:
      mongo-cluster:
        ipv4_address: 172.20.0.4
    volumes:
      - ./mongo-rs/rs_keyfile:/etc/mongodb/pki/keyfile
      - "mongo3_data:/data/db"
      - "mongo_config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: SeedAdmin
      MONGO_INITDB_ROOT_PASSWORD: SeedTest

  backend:
    image: seedtest/seed-test-backend:latest
    ports:
      - "8080:8080"
    container_name: "Seed-backend"
    depends_on:
      - mongo1
    restart: always
    environment:
      FRONTEND_URL: "http://localhost:4200"
      DATABASE_URI: mongodb://SeedAdmin:SeedTest@mongo1:27017/?directConnection=true
      REPORT_DELETION_TIME: 5
      TESTACCOUNT_NAME:
      TESTACCOUNT_REPO:
      TESTACCOUNT_TOKEN:
      SESSION_SECRET: "secretSessionKey"
      JIRA_SECRET: "secretJiraKey"
      JIRA_SALT: "BJ1yJTJ7AFql"
      EMAIL_AUTH:
      EMAIL_PW:
      EMAIL_PORT:
      EMAIL_HOST:
      GITHUB_CLIENT_SECRET:
      GITHUB_CLIENT_ID:
      PASSPORT_GITHUB_LOCAL_PW_FIELD: "id"
      MAX_SAVED_REPORTS:

  frontend:
    image: seedtest/seed-test-frontend:latest
    ports:
      - "4200:4200"
    container_name: "Seed-frontend"
    depends_on:
      - backend
    restart: always
    environment:
      GITHUB_CLIENT_ID:
      VERSION:
      API_SERVER: "http://localhost:8080/api"

volumes:
  seedDB:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo_config:

networks:
  mongo-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"