version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: "Seed-backend"
    # depends_on: 
    #   - selenium
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    container_name: "Seed-frontend"
    depends_on:
      - backend
  # selenium:
  #   image: selenium/standalone-chrome
  #   build: docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome
  #   ports:
  #     - "5900:5900"
  #     - "4444:4444"
  #   container_name: selenium_chrome