version: "2.12"

services:

  seedmongodb:
    container_name: "Seed-MongoDB"
    image: mongo
    volumes:
      - seedDB:/data/db
      - seedDB:/data/configdb
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=SeedAdmin
      - MONGO_INITDB_ROOT_PASSWORD=SeedTest
      - MONGO_INITDB_DATABASE=Seed
    restart: always
  backend:
    build: 
      ./backend
    ports:
      - "${BACKENDPORT}:${BACKENDPORT}"
    container_name: "Seed-backend"
    depends_on:
      - seedmongodb
    restart: always
    
  frontend:
    build: 
      ./frontend
    ports:
      - "${FRONTENDPORT}:${FRONTENDPORT}"
    container_name: "Seed-frontend"
    depends_on:
      - backend
    restart: always
volumes:
  seedDB: