version: "2.12"

services:
  seedmongodb:
    container_name: "seed-MongoDB"
    image: mongo:7.0.15
    volumes:
      - seedDB:/data/db
      - seedDB:/data/configdb
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=SeedAdmin
      - MONGO_INITDB_ROOT_PASSWORD=SeedTest
      - MONGO_INITDB_DATABASE=Seed
    restart: always

  seed-test-backend:
    image: seedtest/seed-test-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20
    ports:
      - "8080:8080"
    container_name: "seed-backend"
    depends_on:
      - seedmongodb
    restart: always
    environment:
      FRONTEND_URL: "http://localhost:4200"
      DATABASE_URI: mongodb://SeedAdmin:SeedTest@seedmongodb:27017
      REPORT_DELETION_TIME: 5
      TESTACCOUNT_NAME:
      TESTACCOUNT_REPO:
      TESTACCOUNT_TOKEN:
      SESSION_SECRET: "secretSessionKey"
      JIRA_SECRET: "secretJiraKey"
      JIRA_SALT: "BJ1yJTJ7AFql"
      EMAIL_AUTH:
      EMAIL_PW:
      EMAIL_PORT:
      EMAIL_HOST:
      GITHUB_CLIENT_SECRET:
      GITHUB_CLIENT_ID:
      PASSPORT_GITHUB_LOCAL_PW_FIELD: "id"
      MAX_SAVED_REPORTS:

  seed-test-frontend:
    image: seedtest/seed-test-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20
    ports:
      - "4200:4200"
    container_name: "seed-frontend"
    depends_on:
      - seed-test-backend
    restart: always
    environment:
      GITHUB_CLIENT_ID:
      VERSION:
      API_SERVER: "http://localhost:8080/api"

volumes:
  seedDB:
