version: "2.12"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE:-$$(date -u +"%Y-%m-%dT%H:%M:%SZ")}
        - VCS_REF=${VCS_REF:-$$(git rev-parse --short HEAD)}
        - IMAGE_NAME=seed-test-backend:latest
    image: seed-test-backend:latest
    ports:
      - "8080:8080"
    container_name: "Seed-backend"
    restart: always
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE:-$$(date -u +"%Y-%m-%dT%H:%M:%SZ")}
        - VCS_REF=${VCS_REF:-$$(git rev-parse --short HEAD)}
        - IMAGE_NAME=seed-test-frontend:latest
    image: seed-test-frontend:latest
    ports:
      - "4200:4200"
    container_name: "Seed-frontend"
    depends_on:
      - backend
    restart: always