version: "2.12"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: "Seed-backend"
    restart: always

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    container_name: "Seed-frontend"
    depends_on:
      - backend
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
      - API_SERVER="http://backend:8080/api"
    restart: always