function stepDefs() {
  return [
    {
      // ToDO: Frontend Implementation of selections! Use of labels & values?
      id: '',
      stepType: 'given',
      label: null,
      type: 'Role',
      pre: 'As a',
      mid: '',
      values: [],
      selection: ['Guest', 'User'],
    },
    {
      id: '',
      stepType: 'given',
      label: null,
      type: 'Website',
      pre: 'I am on the website:',
      mid: '',
      values: [],
    },
    {
      id: '',
      stepType: 'example',
      label: null,
      type: 'Add Variable',
      pre: '',
      mid: '',
      values: [],
    },
    {
      id: '',
      stepType: 'when',
      label: null,
      type: 'Website',
      pre: 'I go to the website:',
      mid: '',
      values: [],
    },
    {
      id: '',
      stepType: 'when',
      label: null,
      type: 'Button',
      pre: 'I click the button:',
      mid: '',
      values: [],
    },
    {
      id: '',
      stepType: 'when',
      label: '',
      type: 'Field',
      pre: 'I insert',
      mid: 'into the field',
      values: [],
    },
    {
      id: '',
      stepType: 'when',
      label: '',
      type: 'Radio',
      pre: 'I select ',
      mid: 'from the selection',
      values: [],
    },
    {
      id: '',
      stepType: 'when',
      label: '',
      type: 'Dropdown',
      pre: 'I select the option',
      mid: 'from the drop-down-menue',
      values: [],
    },
    {
      id: '',
      stepType: 'when',
      label: '',
      type: 'HoverOverAndSelect',
      pre: 'I hover over the element',
      mid: 'and select the option',
      values: [],
    },
    {
      id: '',
      stepType: 'when',
      label: '',
      type: 'Checkbox',
      pre: 'I select from the',
      mid: 'multiple selection, the values',
      values: [],
    },
    {
      id: '',
      stepType: 'then',
      label: null,
      type: 'Website',
      pre: 'So I will be navigated to the website:',
      mid: '',
      values: [],
    },
    {
      id: '',
      stepType: 'then',
      label: '',
      type: 'Text',
      pre: 'So I can see the text',
      mid: 'in the textbox:',
      values: [],
    },
  ];
}

module.exports = stepDefs;
