/**
 * Interface of a user
 */
export interface User {
    /**
     * Object id of the user in the database, generated by MongoDB.
     */
    _id?: any;

    /**
     * Email of the user
     */
    email: string;

    /**
     * Password of the user usually hashed
     */
    password?: string; // Optional, as a GitHub-only user might not have one initially

     /**
     * Flag for password hash transition
     */
    transitioned?: boolean;

    /**
     * Github object of the user if it is connected to github
     */
    github: {
        /** 
         * Token to access the github data of the user
        */
        githubToken: string;

        /**
         * Name of the user in github
         */
        login: string;

        id: number;

        /** 
         * Last used github repository
        */
        githubRepo?: string;
    };

    /**
     * Jira object of the user if it is connected to jira
     */
    jira?: {
        /**
         * Account name of the user
         */
        AccountName: string;

        /**
         * Password of the user usually hashed
         */
        Password: { $binary: { base64: string, subType: string } };
        Password_Nonce: { $binary: { base64: string, subType: string } };
        Password_Tag: { $binary: { base64: string, subType: string } };

        /**
         * Address of the jira host
         */
        Host: string;

        AuthMethod: string;
    };
}
