name: Backup and Upload

on:
  push:
    branches:
      - main

jobs:
  backup-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Backup and Upload
        run: node indexBackup.js
        env: 
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
