name: Backup and Upload

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight (UTC)

jobs:
  backup-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          pwd
          cd actions/backup2jira
          npm install

      - name: Run Backup and Upload
        run: node actions/backup2jira/indexBackup.js
        env: 
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
