name: Start Docker Stack

on:
  push:
    branches:
      - CUC-384-Github-Actions

jobs:
  start-docker-stack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v1

    - name: Build and start Docker stack
      run: |
        chmod +x runDocker.sh
        ./runDocker.sh

    # wait like 1 min for containers to start
    - name: Create .env file
      run: |
        echo "DATABASE_URI=${{DB_URI}}" > .env
        docker cp .env Seed-backend:/app/.env

    # execute npm test in the frontend container
    - name: Run npm test backend
      run: |
        docker exec Seed-backend npm test > testResults.txt

    # execute npm test in the backend container
    - name: Run npm test backend
      run: |
        docker exec Seed-frontend npm test > testResults.txt