name: MS Teams Push Notification
on:
  push:
    branches:
      - "**"
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send simple notification
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: 'Push Notification'
          message: ''
          timestamp: Europe/Berlin
          color: 'info'