name: MS Teams Push Notification
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - "**"
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send simple notification
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: 'Push Notification'
          deploy-card: true
          timestamp: Europe/Berlin
          color: 'info'