on:
  push:
    branches:
      - CUC-384-Github-Actions
name: SonarCloud
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Build and test frontend
        run: |
          cd frontend
          npm install
          npm test > frontend_testresult.txt

      - name: Build and test backend
        run: |
          cd ../backend
          npm install
          npm test > backend_testresult.txt
