on:
  push:
    branches:
      - CUC-384-Github-Actions
name: SonarCloud
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Build and test
        run: |
          cd frontend
          npm install
          npm test

          cd ../backend
          npm install
          npm test