version: "2.12"

services:
  seedmongodb:
    container_name: "Seed-MongoDB"
    image: mongo
    volumes:
      - seedDB:/data/db
      - seedDB:/data/configdb
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=SeedAdmin
      - MONGO_INITDB_ROOT_PASSWORD=SeedTest
      - MONGO_INITDB_DATABASE=Seed
    restart: always

  backend:
    image: seedtest/seed-test-backend:latest
    ports:
      - "8080:8080"
    container_name: "Seed-backend"
    depends_on:
      - seedmongodb
    restart: always
    environment:
      DATABASE_URI: mongodb://SeedAdmin:SeedTest@seedmongodb:27017
      REPORT_DELETION_TIME: 5
      TESTACCOUNT_NAME: 
      TESTACCOUNT_REPO:
      TESTACCOUNT_TOKEN:
      SESSION_SECRET: 'secretSessionKey'
      JIRA_SECRET: 'secretJiraKey'
      JIRA_SALT: 'BJ1yJTJ7AFql'
      Unassigned_AVATAR_URL: 'https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png'
      EMAIL_AUTH:
      EMAIL_PW:
      EMAIL_PORT:
      EMAIL_HOST:
      GITHUB_CLIENT_SECRET:
      GITHUB_CLIENT_ID:
      PASSPORT_GITHUB_LOCAL_PW_FIELD: 'id'
      MAX_SAVED_REPORTS:

  frontend:
    image: seedtest/seed-test-frontend:latest
    ports:
      - "4200:4200"
    container_name: "Seed-frontend"
    depends_on:
      - backend
    restart: always
    environment:
      GITHUB_CLIENT_ID:
      VERSION:

volumes:
  seedDB: